// <auto-generated />
using System;
using JournalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JournalApp.Migrations
{
    [DbContext(typeof(JournalContext))]
    partial class JournalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("JournalApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goals & Dreams"
                        });
                });

            modelBuilder.Entity("JournalApp.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryMoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondaryMood1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondaryMood2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.HasIndex("PrimaryMoodId");

                    b.HasIndex("SecondaryMood1Id");

                    b.HasIndex("SecondaryMood2Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("JournalApp.Models.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Positive",
                            Name = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Positive",
                            Name = "Excited"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Positive",
                            Name = "Relaxed"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Positive",
                            Name = "Grateful"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Positive",
                            Name = "Confident"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Neutral",
                            Name = "Calm"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Neutral",
                            Name = "Thoughtful"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Neutral",
                            Name = "Curious"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Neutral",
                            Name = "Nostalgic"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Neutral",
                            Name = "Bored"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Negative",
                            Name = "Sad"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Negative",
                            Name = "Angry"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Negative",
                            Name = "Stressed"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Negative",
                            Name = "Lonely"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Negative",
                            Name = "Anxious"
                        });
                });

            modelBuilder.Entity("JournalApp.Models.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Streaks");
                });

            modelBuilder.Entity("JournalApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCustom = false,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            IsCustom = false,
                            Name = "Career"
                        },
                        new
                        {
                            Id = 3,
                            IsCustom = false,
                            Name = "Studies"
                        },
                        new
                        {
                            Id = 4,
                            IsCustom = false,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 5,
                            IsCustom = false,
                            Name = "Friends"
                        },
                        new
                        {
                            Id = 6,
                            IsCustom = false,
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = 7,
                            IsCustom = false,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 8,
                            IsCustom = false,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            IsCustom = false,
                            Name = "Personal Growth"
                        },
                        new
                        {
                            Id = 10,
                            IsCustom = false,
                            Name = "Self-care"
                        },
                        new
                        {
                            Id = 11,
                            IsCustom = false,
                            Name = "Hobbies"
                        },
                        new
                        {
                            Id = 12,
                            IsCustom = false,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 13,
                            IsCustom = false,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 14,
                            IsCustom = false,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 15,
                            IsCustom = false,
                            Name = "Spirituality"
                        },
                        new
                        {
                            Id = 16,
                            IsCustom = false,
                            Name = "Birthday"
                        },
                        new
                        {
                            Id = 17,
                            IsCustom = false,
                            Name = "Holiday"
                        },
                        new
                        {
                            Id = 18,
                            IsCustom = false,
                            Name = "Vacation"
                        },
                        new
                        {
                            Id = 19,
                            IsCustom = false,
                            Name = "Celebration"
                        },
                        new
                        {
                            Id = 20,
                            IsCustom = false,
                            Name = "Exercise"
                        },
                        new
                        {
                            Id = 21,
                            IsCustom = false,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 22,
                            IsCustom = false,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 23,
                            IsCustom = false,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 24,
                            IsCustom = false,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 25,
                            IsCustom = false,
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = 26,
                            IsCustom = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 27,
                            IsCustom = false,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 28,
                            IsCustom = false,
                            Name = "Parenting"
                        },
                        new
                        {
                            Id = 29,
                            IsCustom = false,
                            Name = "Projects"
                        },
                        new
                        {
                            Id = 30,
                            IsCustom = false,
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 31,
                            IsCustom = false,
                            Name = "Reflection"
                        });
                });

            modelBuilder.Entity("JournalApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JournalApp.Models.JournalEntry", b =>
                {
                    b.HasOne("JournalApp.Models.Category", "Category")
                        .WithMany("JournalEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JournalApp.Models.Mood", "PrimaryMood")
                        .WithMany()
                        .HasForeignKey("PrimaryMoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JournalApp.Models.Mood", "SecondaryMood1")
                        .WithMany()
                        .HasForeignKey("SecondaryMood1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JournalApp.Models.Mood", "SecondaryMood2")
                        .WithMany()
                        .HasForeignKey("SecondaryMood2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("PrimaryMood");

                    b.Navigation("SecondaryMood1");

                    b.Navigation("SecondaryMood2");
                });

            modelBuilder.Entity("JournalApp.Models.Category", b =>
                {
                    b.Navigation("JournalEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
